snapcraft: drop dnsmasq docs
due to:
FileNotFoundError: [Errno 2] No such file or directory: '/build/network-manager-snap-20/stage/usr/share/doc/dnsmasq'

because the package isn't primed